### ISSUE TITLE
Not able to run this in localhost.

### ISSUE THREAD

**Issue by Shekharrajak** [parkeragee/hire-remotely#1]
I hope I have install all the dependencies ,but still I am not able to run this project in my localhost.
Error :  

module.js:338
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (hire-remotely\node_modules\sails\lib\app\i
ndex.js:6:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

What's the problem here ?

**Comment by parkeragee** [comment]
Hey @Shekharrajak I haven't maintained this code at all, but it looks like you're just missing a node_module. It should live here:

```
├── hire-remotely
│   ├── node_modules
│   │   ├── sails
│   │   │   ├── node_modules
│   │   │   │   ├── async
```

I would check to see if it's in that directory after installing all the dependencies. If it's not, just `cd` into `hire-remotely/node_modules/sails` and `npm install async --save`.

Hope that helps you out.

I've been thinking about updating this app to the latest version of Sails, but I don't have that free time as of now.

**Comment by Shekharrajak** [comment]
I have done this.I think I miss 1 or 2 dependencies.
